version: '3'

run: when_changed

includes:
  rust-shared:
    taskfile: ../../extra/taskfile/Rust-Taskfile.yml
    flatten: true

vars:
  PROJECT_ROOT: ../../
  SWIFT_DIR: ./swift
  APPLE_PROJECT_RUST_DIR: ../../safari/YomikiriTokenizer/rust

  IOS_TARGETS:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim

  INSTALLED_TARGETS:
    sh: rustup show

tasks:
  build:ios:
    deps: [_clean-if-release]
    cmds:
      - task: generate:uniffi
        vars:
          LANGUAGE: swift
          OUT_DIR: '{{.SWIFT_DIR}}'
      - 'mkdir -p "{{.APPLE_PROJECT_RUST_DIR}}"'
      - 'cp -r {{.SWIFT_DIR}}/* "{{.APPLE_PROJECT_RUST_DIR}}/"'
      - task: _rustup_install_targets
        vars:
          TARGETS_VAR: IOS_TARGETS
      - task: _build:lib
        vars:
          FLAG_TARGET: '{{range $i, $val := .IOS_TARGETS}}--target {{$val}} {{end}}'

  # Rust lib build skip is delegated to cargo
  _build:lib:
    internal: true
    requires:
      vars: [FLAG_TARGET]
    vars:
      FLAG_RELEASE: '{{if .RELEASE}}--release{{end}}'
    cmds:
      - 'cargo build --lib {{.FLAG_RELEASE}} {{.FLAG_TARGET}}'

  generate:uniffi:
    requires:
      vars: [LANGUAGE, OUT_DIR]
    deps:
      - task: _build:lib
        vars:
          FLAG_TARGET: ''
    cmds:
      - task: _generate:uniffi
        vars:
          LANGUAGE: '{{.LANGUAGE}}'
          OUT_DIR: '{{.OUT_DIR}}'

  _generate:uniffi:
    internal: true
    requires:
      vars: [LANGUAGE, OUT_DIR]
    vars:
      RELEASE_SEG: '{{if .RELEASE}}release{{else}}debug{{end}}'
      LIB_DIR: '../../target/{{.RELEASE_SEG}}'
      SO_PATH: '{{.LIB_DIR}}/libyomikiri_backend_uniffi.so'
      DYLIB_PATH: '{{.LIB_DIR}}/libyomikiri_backend_uniffi.dylib'
      # Lib may be .so on linux and .dylib on macos
      LIB_PATH:
        sh: |
          if [ -f "{{.DYLIB_PATH}}" ]; then
            echo "{{.DYLIB_PATH}}"
          elif [ -f "{{.SO_PATH}}" ]; then
            echo "{{.SO_PATH}}"
          else
            echo "{{.LIB_DIR}}/__ERROR_COULD_NOT_FIND_BUILT_LIB_FILE"
          fi
    sources:
      - '{{.LIB_PATH}}'
      - './Cargo.toml'
    generates:
      - '{{.OUT_DIR}}/**/*'
    cmds:
      - '
        cargo run --features "uniffi/cli uniffi-bindgen"
        --bin uniffi-bindgen generate --language "{{.LANGUAGE}}"
        --library "{{.LIB_PATH}}" --out-dir "{{.OUT_DIR}}"
        '

  # Cleans dir if `{{.RELEASE}}` is set
  _clean-dir-if-release:
    internal: true
    requires:
      vars: [DIR]
    cmds:
      - '{{if .RELEASE}}rm -rf {{.DIR}}{{end}}'

  clean:
    - 'rm -rf {{.SWIFT_DIR}} {{.APPLE_PROJECT_RUST_DIR}}'

  _rustup_install_targets:
    internal: true
    requires:
      vars: [TARGETS_VAR]
    cmds:
      - for:
          var: '{{.TARGETS_VAR}}'
        task: '{{if contains .ITEM .INSTALLED_TARGETS}}_void{{else}}_rustup_install{{end}}'
        vars:
          TARGET: '{{.ITEM}}'

  _rustup_install:
    internal: true
    requires:
      vars: [TARGET]
    cmds:
      - 'rustup target add {{.TARGET}}'
