version: '3'

includes:
  rust-shared:
    taskfile: ../../extra/taskfile/Rust-Taskfile.yml
    flatten: true

run: when_changed

vars:
  ROOT: '../..'
  DICTIONARY_FILES_DIR: '{{.ROOT}}/generated/dictionary-files'
  ORIGINAL_DIR: '{{.ROOT}}/generated/unidic-original'
  TRANSFORM_DIR: '{{.ROOT}}/generated/unidic-transformed'
  OUTPUT_DIR: '{{.ROOT}}/generated/unidic-output'
  CRATE_BINARY: '{{.ROOT}}/target/release/yomikiri-unidic'

tasks:
  generate:
    sources:
      - '{{.CRATE_BINARY}}'
      - '{{.DICTIONARY_FILES_DIR}}/**/*'
      - '{{.ORIGINAL_DIR}}/**/*'
      - exclude: '**/.*'
    generates:
      - '{{.TRANSFORM_DIR}}/**/*'
      - '{{.OUTPUT_DIR}}/**/*'
    cmds:
      - '"{{.CRATE_BINARY}}" --clean --unidic-dir="{{.ORIGINAL_DIR}}" --transform-dir="{{.TRANSFORM_DIR}}" --output-dir="{{.OUTPUT_DIR}}" --resource-dir="{{.DICTIONARY_FILES_DIR}}"'

  _build:
    cmds:
      - 'cargo build --release'
