version: '3'

includes:
  rust-shared:
    taskfile: ../../extra/taskfile/Rust-Taskfile.yml
    flatten: true

run: when_changed

vars:
  ROOT: '../..'
  DICTIONARY_FILES_DIR: '{{.ROOT}}/generated/dictionary-files'
  ORIGINAL_DIR: '{{.ROOT}}/generated/unidic-original'
  TRANSFORM_DIR: '{{.ROOT}}/generated/unidic-transformed'
  OUTPUT_DIR: '{{.ROOT}}/generated/unidic-output'

tasks:
  generate:
    internal: true
    sources:
      - '../../Cargo.toml'
      - '../../Cargo.lock'
      - './Cargo.toml'
      - './src/**/*'
      - '{{.DICTIONARY_FILES_DIR}}/**/*'
      - '{{.ORIGINAL_DIR}}/**/*'
      - exclude: '**/.*'
    generates:
      - '{{.TRANSFORM_DIR}}/**/*'
      - '{{.OUTPUT_DIR}}/**/*'
    cmds:
      - 'cargo run --release -- --clean --unidic-dir="{{.ORIGINAL_DIR}}" --transform-dir="{{.TRANSFORM_DIR}}" --output-dir="{{.OUTPUT_DIR}}" --resource-dir="{{.DICTIONARY_FILES_DIR}}"'
