version: '3'

includes:
  rust-shared:
    taskfile: ../../extra/taskfile/Rust-Taskfile.yml
    flatten: true
  consts:
    taskfile: '../../extra/taskfile/Consts-Taskfile.yml'

vars:
  ROOT: '../..'
  DICTIONARY_FILES_DIR: '{{.ROOT}}/{{.__YOMIKIRIDICT_DIR}}'
  ORIGINAL_DIR: '{{.ROOT}}/{{.__UNIDIC_ORIGINAL_DIR}}'
  TRANSFORM_DIR: '{{.ROOT}}/{{.__UNIDIC_TRANSFORMED_DIR}}'
  OUTPUT_DIR: '{{.ROOT}}/{{.__UNIDIC_OUTPUT_DIR}}'
  CRATE_BINARY: '{{.ROOT}}/target/release/yomikiri-unidic'

tasks:
  generate:
    cmds:
      - task: _build
      - task: _generate

  _build:
    run: when_changed
    cmds:
      - 'cargo build --release'

  _generate:
    sources:
      - '{{.CRATE_BINARY}}'
      - '{{.DICTIONARY_FILES_DIR}}/**/*'
      - '{{.ORIGINAL_DIR}}/**/*'
      - exclude: '**/.*'
    generates:
      - '{{.TRANSFORM_DIR}}/**/*'
      - '{{.OUTPUT_DIR}}/**/*'
    cmds:
      - '"{{.CRATE_BINARY}}" --clean --unidic-dir="{{.ORIGINAL_DIR}}" --transform-dir="{{.TRANSFORM_DIR}}" --output-dir="{{.OUTPUT_DIR}}" --resource-dir="{{.DICTIONARY_FILES_DIR}}"'
