[workspace]
members = [
  "rust",
  "dictionary",
  "dictionary-types",
  "unidic",
  "extra/generate-license/rust",
]
resolver = "2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "z"
