[workspace]
members = [
  "crates/yomikiri-backend",
  "crates/jmdict",
  "crates/dictionary",
  "crates/unidic",
  "crates/unidic-types",
  "extra/generate-license/rust",
]
resolver = "2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "z"

[workspace.lints.clippy]
needless_borrows_for_generic_args = "allow"
