packages:
  - "main"
  - "crates/yomikiri-dictionary"
  - "crates/yomikiri-dictionary/pkg"
  - "crates/jmdict"
  - "crates/unidic"
  - "crates/yomikiri-backend"
  - "crates/yomikiri-backend/pkg"
  - "crates/yomikiri-dictionary-generator"
  - "crates/yomikiri-dictionary-generator/files"
  - "extra/generate-license"
