packages:
  - 'main'
  - 'crates/yomikiri-dictionary'
  - 'crates/yomikiri-dictionary/pkg'
  - 'crates/jmdict'
  - 'crates/unidic'
  - 'crates/unidic-types'
  - 'crates/yomikiri-backend'
  - 'crates/yomikiri-backend/bindings'
  - 'crates/yomikiri-backend/pkg'
  - 'crates/yomikiri-dictionary-generator'
  - 'crates/yomikiri-dictionary-generator/files'
  - 'extra/generate-license'
