version: '3'

includes:
  main:
    taskfile: './main/Taskfile.yml'
    dir: './main'
  japanese-utils:
    taskfile: './crates/japanese-utils/Taskfile.yml'
    dir: './crates/japanese-utils'
  jmdict:
    taskfile: './crates/jmdict/Taskfile.yml'
    dir: './crates/jmdict'
  unidic:
    taskfile: './crates/unidic/Taskfile.yml'
    dir: './crates/unidic'
  unidic-types:
    taskfile: './crates/unidic-types/Taskfile.yml'
    dir: './crates/unidic-types'
  yomikiri-backend:
    aliases: [backend]
    taskfile: './crates/yomikiri-backend/Taskfile.yml'
    dir: './crates/yomikiri-backend'
  yomikiri-dictionary:
    taskfile: './crates/yomikiri-dictionary/Taskfile.yml'
    dir: './crates/yomikiri-dictionary'
  yomikiri-dictionary-generator:
    taskfile: './crates/yomikiri-dictionary-generator/Taskfile.yml'
    dir: './crates/yomikiri-dictionary-generator'

tasks:
  print-version:
    desc: Print version in root package.json
    cmds:
      - tsx './extra/scripts/print-version.ts'

  format:prettier:
    aliases: ['fmt:prettier']
    desc: 'Format files using prettier'
    cmds:
      - 'pnpm prettier --write --list-different .'

  format:rust:
    aliases: ['fmt:rust']
    desc: 'Format files using Cargo (Rust)'
    cmds:
      - 'cargo fmt'

  format:
    aliases: ['fmt']
    desc: 'Format all files'
    deps: ['format:prettier', 'format:rust']

  check-format:prettier:
    aliases: ['check-fmt:prettier']
    cmds:
      - pnpm prettier --check .

  check-format:rust:
    aliases: ['check-fmt:rust']
    cmds:
      - cargo fmt --check

  check-format:
    aliases: ['check-fmt']
    desc: 'Check if files are formatted'
    deps: [check-format:js, check-format:rust]
