version: '3'

tasks:
  build:shared:
    internal: true
    requires:
      vars:
        - name: 'NODE_ENV'
          enum: ['production', 'development']
        - name: 'PLATFORM'
          enum: ['firefox', 'chrome', 'ios', 'iosapp']
    cmds:
      - 'NODE_ENV={{.NODE_ENV}} TARGET_PLATFORM={{.PLATFORM}} pnpm tsx esbuild.config.ts'

  build:firefox:
    desc: 'Build for firefox'
    deps:
      - task: 'build:shared'
        vars:
          NODE_ENV: 'production'
          PLATFORM: 'firefox'

  build:chrome:
    desc: 'Build for Chrome'
    deps:
      - task: 'build:shared'
        vars:
          NODE_ENV: 'production'
          PLATFORM: 'chrome'

  build:ios:
    desc: 'Build for ios'
    deps:
      - task: 'build:shared'
        vars:
          NODE_ENV: 'production'
          PLATFORM: 'ios'

  build:iosapp:
    desc: 'Build for iosapp'
    deps:
      - task: 'build:shared'
        vars:
          NODE_ENV: 'production'
          PLATFORM: 'iosapp'

  dev:chrome:
    aliases: ['dev']
    desc: 'Dev build for Chrome'
    deps:
      - task: 'build:shared'
        vars:
          NODE_ENV: 'development'
          PLATFORM: 'chrome'

  dev:firefox:
    desc: 'Dev build for firefox'
    deps:
      - task: 'build:shared'
        vars:
          NODE_ENV: 'development'
          PLATFORM: 'firefox'

  dev:ios:
    desc: 'Dev build for ios'
    deps:
      - task: 'build:shared'
        vars:
          NODE_ENV: 'development'
          PLATFORM: 'ios'

  dev:iosapp:
    desc: 'Dev build for iosapp'
    deps:
      - task: 'build:shared'
        vars:
          NODE_ENV: 'development'
          PLATFORM: 'iosapp'

  test:
    desc: 'Test'
    cmds:
      - 'pnpm vitest run'

  check:
    deps: ['check:ts', 'check:svelte']

  check:ts:
    cmds:
      - 'pnpm tsc --noemit'

  check:svelte:
    vars:
      WARNINGS: 'a11y-no-static-element-interactions:ignore'
    cmds:
      - 'pnpm svelte-check --compiler-warnings "{{.WARNINGS}}"'

  lint:
    cmds:
      - 'pnpm eslint --cache .'

  format:
    aliases: ['fmt']
    cmds:
      - 'pnpm -w prettier --write --list-different "$PWD"'
