version: '3'

run: 'when_changed'

includes:
  rust-shared:
    taskfile: ../../extra/taskfile/Rust-Taskfile.yml
    flatten: true

vars:
  PROJECT_ROOT: '../../'
  ROOT_CARGO_TOML: '../../Cargo.toml'
  ROOT_CARGO_LOCK: '../../Cargo.lock'
  WASM_DIR: './pkg'

  TARGET_WASM: 'wasm32-unknown-unknown'

tasks:
  generate:
    desc: Build wasm backend
    cmds:
      - task: _clean-dir-if-release
        vars:
          DIR: '{{.WASM_DIR}}'
      - 'wasm-pack build {{if not .RELEASE}}--dev{{end}} -d "{{.WASM_DIR}}" --scope yomikiri --target web'

  generate:release:
    desc: Build wasm backend for release
    cmds:
      - task: generate:wasm
        vars:
          RELEASE: '1'

  clean:
    desc: Remove build artifacts created by taskfile.
    cmds:
      - 'rm -rf {{.WASM_DIR}}'

  # Cleans dir if `{{.RELEASE}}` is set
  _clean-dir-if-release:
    internal: true
    requires:
      vars: [DIR]
    cmds:
      - task: '{{if .RELEASE}}_clean-dir{{else}}_void{{end}}'
        vars:
          DIR: '{{.DIR}}'

  _clean-dir:
    internal: true
    requires:
      vars: [DIR]
    cmds:
      - 'rm -rf {{.DIR}}'
