[package]
name = "yomikiri-unidic-dictionary"
version = "0.1.0"
edition = "2021"

[features]
real = []


[dependencies]
lindera-core = "0.27"

[build-dependencies]
yomikiri-unidic-build = { path = "./unidic-build"}
walkdir = "2.3"
filetime = "0.2"