[package]
name = "yomikiri-unidic-dictionary"
version = "0.1.0"
edition = "2021"

[features]
real = []


[dependencies]
lindera-core = "0.27"

[build-dependencies]
yomikiri-unidic-build = { path = "./unidic-build"}


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "z"