[package]
name = "yomikiri-jmdict"
version = "0.1.0"
edition = "2021"
description = "JMDict XML Types"
license = "MIT"

[dependencies]
rustyxml = { workspace = true }
regex = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
