[package]
name = "yomikiri-jmdict"
version = "0.1.0"
edition = "2021"
description = "JMDict XML Types"
license = "MIT"

[dependencies]
bincode = { workspace = true }
thiserror = { workspace = true }
lazy_static = { workspace = true }
quick-xml = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[lints]
workspace = true
