[package]
name = "yomikiri-dictionary-generator"
version = "0.1.0"
edition = "2021"
description = "Generate or download yomikiri dictionary files"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ureq = "2.7"
tempfile = "3.8"
anyhow = "1"
flate2 = "1"
chrono = { version = "0.4", features = ["alloc"] }
yomikiri-dictionary = { path = "../yomikiri-dictionary" }

[lints]
workspace = true
