version: '3'

includes:
  rust-shared:
    taskfile: ../../extra/taskfile/Rust-Taskfile.yml
    flatten: true

vars:
  PROJECT_ROOT: '../..'
  JMDICT_DIR: '{{.PROJECT_ROOT}}/generated/jmdict'
  YOMIKIRIDICT_PATH: '{{.PROJECT_ROOT}}/generated/dictionary-files/english.yomikiridict'

tasks:
  download:
    # Build-skipping is done within rust script
    desc: Downloads jmdict file if it does not exist at output path
    cmds:
      - 'cargo run --release -- download --outdir="{{.JMDICT_DIR}}"'

  fresh:
    desc: Force downloads a fresh jmdict file
    cmds:
      - 'cargo run --release -- download --outdir="{{.JMDICT_DIR}} --new"'

  generate:
    desc: Generate dictionary file from jmdict file
    sources:
      - '../../Cargo.toml'
      - '../../Cargo.lock'
      - 'Cargo.toml'
      - 'src/**/*.rs'
      - '{{.JMDICT_DIR}}/**/*'
      - exclude: '**/.*'
    generates:
      - '{{.YOMIKIRIDICT_PATH}}'
    cmds:
      - 'cargo run --release -- generate --rawdir="./{{.JMDICT_DIR}}" --out="{{.YOMIKIRIDICT_PATH}}"'

  download-and-generate:
    desc: 'Generate dictionary file. Download JMDICT if it does not exist.'
    cmds:
      - task: 'download'
      - task: 'generate'
