version: '3'

includes:
  rust-shared:
    taskfile: ../../extra/taskfile/Rust-Taskfile.yml
    flatten: true
    excludes: [check, lint]

tasks:
  check:
    cmds:
      - cargo check
      - cargo check --target wasm32-unknown-unknown

  lint:
    cmds:
      - cargo clippy
      - cargo clippy  --target wasm32-unknown-unknown
