# Manual additions to THIRD_PARTY licenses

[[res]]
name = "UniDic"
url = "https://clrd.ninjal.ac.jp/unidic/en/"
license = "BSD"
text = """
Copyright (c) 2011-2017, The UniDic Consortium
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

 * Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the
   distribution.

 * Neither the name of the UniDic Consortium nor the names of its
   contributors may be used to endorse or promote products derived
   from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

[[res]]
name = "JMDict, JMneDict"
url = "https://www.edrdg.org/wiki/index.php/JMdict-EDICT_Dictionary_Project"
license = "CC-BY-SA-4.0 | Custom"
text = """
The JMDict, JMneDict dictionary files are the property of the <a href='https://www.edrdg.org/'>Electronic Dictionary Research and Development Group</a>, and are used in conformance with the Group's <a href='https://www.edrdg.org/edrdg/licence.html'>license.</a>

The dictionary files are made available under a Creative Commons Attribution-ShareAlike Licence (V4.0). The Licence Deed can be viewed here (https://creativecommons.org/licenses/by-sa/4.0/), and the full Licence Code is here (https://creativecommons.org/licenses/by-sa/4.0/legalcode). 

For attribution of these files, you must:
  a. in the case of publishing significant extracts of the files, or material based on significant extracts of the files, e.g. in a published dictionary or in vocabulary lists, clearly acknowledge that you used the files for this purpose;
  b. in the case of a software package, WWW server, smartphone app, etc. which uses the files or incorporates data from the files, you must:
          i. acknowledge the usage and source of the files in the documentation, publicity material, WWW site of the package/server, etc.;
        ii. provide copies of the documentation and licence files (in the case of software packages). Where the application packaging does not provide for the inclusion of such files (e.g. with iPhone applications), it is sufficient to provide links, as per the next point;
            provide links to either local copies of the documentation and licence files or to the locations of the files at Monash University or at the EDRDG site.
        iii. If a WWW server is providing a dictionary function or an on-screen display of words from the files, the acknowledgement must be made on each screen display, e.g. in the form of a message at the foot of the screen or page. If, however, material from the files is mixed with information from other sources, it is sufficient to provide a general acknowledgement of the sources as described above.
            For smartphone and tablet apps, acknowledgement must be made, e.g. on a separate screen accessed from a menu, such as one labelled "About", "Sources", etc. It is not sufficient just to mention it on a start-up/launch page of the app.
            For the EDICT, JMdict and KANJIDIC files, the following URLs may be used or quoted:
            https://www.edrdg.org/wiki/index.php/JMdict-EDICT_Dictionary_Project
            https://www.edrdg.org/wiki/index.php/KANJIDIC_Project

See this page (http://www.edrdg.org/edrdg/sample.html) for samples of possible acknowledgement text.
Note that in all cases, the addition of material to the files or to extracts from the files does not remove or in any way diminish the Group's copyright over the files. Users of material from the files must NOT claim copyright over that material.
Note also that provided the conditions above are met, there is NO restriction placed on commercial use of the files. The files can be bundled with software and sold for whatever the developer wants to charge. Software using these files does not have to be under any form of open-source licence.
Where use of the files results in a financial return to the user, it is suggested that the user make a donation to the Group to assist with the continued development of the files. The only method currently available is to make a donation via PayPal using a credit or debit card. Simply click on the following button and follow the instructions. 
"""
text_html = true

[[res]]
name = "ionicons"
url = "https://ionic.io/ionicons"
license = "MIT"
text = """
The MIT License (MIT)

Copyright (c) 2015-present Ionic (http://ionic.io/)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""
