// Re-export all messaging functions and types
export {
  BackgroundFunction,
  ExtensionMessaging,
  type MessageHandler,
  type MessageSender,
  NonContentScriptFunction,
} from "./message";

// Re-export all browser API functions and types
export {
  activeTab,
  type ApiInitializeOptions,
  browserAction,
  browserStorage,
  createConnection,
  currentTab,
  currentTabId,
  type ExecutionContext,
  extensionManifest,
  getStorage,
  getTabs,
  goToTab,
  handleActionClicked,
  handleBrowserLoad,
  handleConnection,
  handleInstall,
  handleStorageChange,
  japaneseTtsVoices,
  type Port,
  removeStorage,
  removeTab,
  setActionIcon,
  setBadge,
  setStorage,
  speakJapanese,
  type StorageHandler,
  type StorageKey,
  updateTab,
} from "./browserApi";
