version: '3'

vars:
  PROJECT_ROOT: ../../
  GENERATED_DIR: '{{.PROJECT_ROOT}}/generated'
  GENERATED_LICENSE_DIR: '{{.GENERATED_DIR}}/license'

tasks:
  generate:
    desc: 'Generate licenses text'
    run: once
    cmds:
      - 'pnpm tsx index.ts > "{{.GENERATED_LICENSE_DIR}}/THIRD_PARTY.txt"'

  check:
    desc: 'Check files'
    cmds:
      - 'cargo check'
    dir: './rust'

  lint:
    desc: 'Lint files'
    cmds:
      - 'pnpm tsc --noemit'
      - 'pnpm eslint --cache .'
      - task: 'lint:rust'

  lint:rust:
    cmds:
      - cargo clippy -- -D warnings
    dir: './rust'

  test:
    silent: true

  format:
    aliases: ['fmt']
    cmds:
      - 'pnpm -w prettier --write --list-different "$PWD"'
      - task: 'format:rust'

  format:rust:
    cmds:
      - cargo fmt
    dir: './rust'
