version: '3'

run: when_changed

vars:
  PROJECT_ROOT: '../..'
  GENERATED_DIR: '{{.PROJECT_ROOT}}/generated'
  GENERATED_LICENSE_DIR: '{{.GENERATED_DIR}}/license'
  LICENSE_FILE: '{{.GENERATED_LICENSE_DIR}}/THIRD_PARTY.txt'

tasks:
  generate:
    desc: 'Generate licenses text'
    sources:
      - '{{.PROJECT_ROOT}}/pnpm-lock.yaml'
      - '{{.PROJECT_ROOT}}/Cargo.toml'
      - '{{.LICENSE_FILE}}'
      - 'exclude:**/.*'
    generates:
      - '{{.LICENSE_FILE}}'
    cmds:
      - 'pnpm tsx index.ts > "{{.LICENSE_FILE}}"'

  check:
    desc: 'Check files'
    cmds:
      - 'cargo check'
    dir: './rust'

  lint:
    desc: 'Lint files'
    cmds:
      - 'pnpm tsc --noemit'
      - 'pnpm eslint --cache .'
      - task: 'lint:rust'

  lint:rust:
    cmds:
      - cargo clippy -- -D warnings
    dir: './rust'

  test:
    silent: true

  format:
    aliases: ['fmt']
    cmds:
      - 'pnpm -w prettier --write --list-different "$PWD"'
      - task: 'format:rust'

  format:rust:
    cmds:
      - cargo fmt
    dir: './rust'
