name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

env:
  DPRINT_CACHE_DIR: ${{ github.workspace }}/.dprint

jobs:
  test:
    runs-on: macos-14
    timeout-minutes: 45
    name: 'Lint, Test, Build web extension'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install cargo
        uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0 # v1.85.1
        with:
          toolchain: 1.85.0
          components: clippy, rustfmt
      
      - name: Install cargo binstall
        uses: cargo-bins/cargo-binstall@c5b9ad0629490ed87096ffcb99f215ef349b9cdb
      
      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install pnpm deps
        run: pnpm install

      - name: Get version
        id: version
        run: echo "VERSION=$(task --silent print-version)" >> "$GITHUB_OUTPUT"

      - name: Hash root Cargo.toml and Cargo.lock
        id: cargo-hash
        run: echo "HASH=${{hashFiles('./Cargo.lock', './Cargo.toml')}}" >> "$GITHUB_OUTPUT"

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8

      - name: Cache Task Checksums
        uses: actions/cache@v4
        with:
          path: .task/
          key: ${{runner.os}}-task-checksum
      
      - name: Cache generated directory
        uses: actions/cache@v4
        with:
          path: generated/
          key: ${{runner.os}}-generated-dir

      - name: Cache dprint
        uses: actions/cache@v4
        with:
          path: ${{ env.DPRINT_CACHE_DIR }}
          key: ${{ runner.os }}-dprint-${{hashFiles('**/pnpm-lock.yaml', '**/dprint.json')}}
          restore-keys: |
            ${{ runner.os }}-dprint-

      - name: Cache generated/
        uses: actions/cache@v4
        with:
          path: generated/
          key: generated

      - name: Formatting
        run: task --verbose check-format

      - name: Install Cargo ndk
        run: cargo binstall cargo-ndk --no-confirm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install wasm-pack
        run: pnpm add -g wasm-pack

      - name: Build
        run: task --verbose build:all

      - name: Lint
        run: task --verbose lint

      - name: Test
        run: task --verbose test
