name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 45
    name: "Lint, Test, Build web extension"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: "next-9"

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install cargo
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios

      - name: Install pnpm deps
        run: pnpm install

      - name: Get version
        id: version
        run: echo "VERSION=$(pnpm run --silent print-version)" >> "$GITHUB_OUTPUT"

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84

      - name: Install wasm-pack
        run: pnpm add -g wasm-pack

      - name: Cache unidic
        uses: actions/cache@v4
        with:
          path: crates/unidic/original
          key: unidic-2.1.2

      - name: Cache jmdict
        uses: actions/cache@v4
        with:
          path: crates/yomikiri-dictionary-generator/jmdict/jmdict_english.xml
          key: jmdict-english-xml-${{steps.version.outputs.output}}

      - name: Construct
        run: pnpm run construct:all


      - name: Generate licenses
        run: pnpm run generate-licenses
      
      - name: Formatting
        run: pnpm run check-format

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Build web
        run: pnpm run build:chrome && pnpm run build:firefox && pnpm run build:ios
