name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 15
    name: "Lint, Test, Build web extension"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install cargo
        run: rustup toolchain install stable

      - name: Install pnpm deps
        run: pnpm install

      - name: Construct
        run: pnpm run construct:all

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Build web
        run: pnpm run build:chrome && pnpm run build:firefox && pnpm run build:ios
