name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  JMDICT_PATH: crates/yomikiri-dictionary-generator/jmdict/jmdict_english.xml
  JMNEDICT_PATH: crates/yomikiri-dictionary-generator/jmdict/jmnedict.xml
  DICTIONARY_PATH: crates/yomikiri-dictionary-generator/files/english.yomikiridict
  UNIDIC_OUTPUT_PATH: crates/unidic/output

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 45
    name: 'Lint, Test, Build web extension'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Install pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 'next-9'

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install cargo
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios

      - name: Install pnpm deps
        run: pnpm install

      - name: Get version
        id: version
        run: echo "VERSION=$(pnpm task --silent print-version)" >> "$GITHUB_OUTPUT"

      - name: Hash root Cargo.toml and Cargo.lock
        id: cargo-hash
        run: echo "HASH=${{hashFiles('./Cargo.lock', './Cargo.toml')}}" >> "$GITHUB_OUTPUT"

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84

      - name: Formatting
        run: pnpm task check-format

      - name: Install wasm-pack
        run: pnpm add -g wasm-pack

      - name: Cache unidic
        uses: actions/cache@v4
        with:
          path: crates/unidic/original
          key: unidic-2.1.2

      - name: Cache jmdict
        uses: actions/cache@v4
        with:
          path: ${{env.JMDICT_PATH}}
          key: jmdict-english-xml-${{steps.version.outputs.VERSION}}

      - name: Cache jmnedict
        uses: actions/cache@v4
        with:
          path: ${{env.JMNEDICT_PATH}}
          key: jmnedict-xml-${{steps.version.outputs.VERSION}}

      - name: Cache yomikiri dictionary
        uses: actions/cache@v4
        id: cache-yomikiri-dictionary
        with:
          path: ${{env.DICTIONARY_PATH}}
          key: yomikiridict-${{ steps.cargo-hash.outputs.HASH }}-${{ hashFiles('./crates/dictionary-generator/src/**/*', './crates/dictionary-generator/Cargo.toml', env.JMDICT_PATH, env.JMNEDICT_PATH) }}

      - name: Lint
        run: pnpm task lint

      - name: Test
        run: pnpm task test

      - name: Build
        run: pnpm task build:all
