name: Create JMDict

on:
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

jobs:
  download_jmdict:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Download JMDict"
    steps:
      - name: Download JMDict
        run: curl -O "http://ftp.edrdg.org/pub/Nihongo/JMdict_e.gz"

      - name: Download JMneDict
        run: curl -O "http://ftp.edrdg.org/pub/Nihongo/JMnedict.xml.gz"

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            "JMdict_e.gz"
            "JMnedict.xml.gz"

      - name: Get current date
        id: date
        run: echo $(date '+%Y-%m-%d') >> "$GITHUB_OUTPUT"

      - name: Create Github Release
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048 # v2.2.0
        with:
          prerelease: true
          tag_name: "jmdict-${{ steps.date.outputs.stdout }}"
          files: |
            "JMdict_e.gz"
            "JMnedict.xml.gz"
