name: Create JMDict

on:
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write
  contents: write # gh-release

jobs:
  download_jmdict:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Download JMDict"
    steps:
      - name: Get current date
        id: date
        run: echo "DATE=$(date '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Download JMDict
        run: curl "http://ftp.edrdg.org/pub/Nihongo/JMdict_e.gz" -o "JMdict_e.gz"

      - name: Download JMneDict
        run: curl "http://ftp.edrdg.org/pub/Nihongo/JMnedict.xml.gz" -o "JMnedict.xml.gz"

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            JMdict_e.gz
            JMnedict.xml.gz

      - name: Create Github Release
        uses: softprops/action-gh-release@e7a8f85e1c67a31e6ed99a94b41bd0b71bbee6b8 # v2.0.9
        with:
          tag_name: "jmdict-${{ steps.date.outputs.DATE }}"
          name: "JMDict ${{ steps.date.outputs.DATE }}"
          body: "JMDict dictionary files used in Yomikiri"
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            JMdict_e.gz
            JMnedict.xml.gz
