name: Create JMDict

on:
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write
  contents: write # gh-release

jobs:
  download_jmdict:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Download JMDict"
    steps:
      - name: Get current date
        id: date
        run: echo "DATE=$(date '+%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Download JMDict
        run: curl "http://ftp.edrdg.org/pub/Nihongo/JMdict_e.gz" -o "JMdict_e.gz"

      - name: Download JMneDict
        run: curl "http://ftp.edrdg.org/pub/Nihongo/JMnedict.xml.gz" -o "JMnedict.xml.gz"

      - name: Print files
        run: ls -l

      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            "JMdict_e.gz"
            "JMnedict.xml.gz"

      - name: Create Github Release
        uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048 # v2.2.0
        with:
          tag_name: "jmdict-${{ steps.date.outputs.DATE }}"
          name: "JMDict ${{ steps.date.outputs.DATE }}"
          body: "JMDict dictionary files used in Yomikiri"
          draft: true
          fail_on_unmatched_files: true
          files: |
            "JMdict_e.gz"
            "JMnedict.xml.gz"
